repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: detect-private-key
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [--autofix]
    - id: requirements-txt-fixer

- repo: https://github.com/hadialqattan/pycln
  rev: v1.2.5
  hooks:
    - id: pycln
      args: [ --all ]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      language_version: python39
      args: [ -l 119 ]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [ --profile, black ]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: [flake8-isort==4.0.0, flake8-quotes==3.0.0, flake8-print==3.1.4]
